# Generated by Django 3.1.5 on 2021-09-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_user',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=100)),
                ('password', models.CharField(db_column='password', max_length=100)),
                ('contact_number', models.CharField(db_column='contact_number', max_length=12)),
                ('email', models.CharField(db_column='email', max_length=100)),
            ],
        ),
    ]
