# Generated by Django 3.1.5 on 2021-09-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_user',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='login_user',
            name='address',
            field=models.CharField(db_column='address', default='sads', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login_user',
            name='conform_password',
            field=models.CharField(db_column='conform_password', default=12, max_length=100),
            preserve_default=False,
        ),
    ]
